func backtrack() { throw; }
func throwString(s) { throw s; }

try { backtrack(); }
catch err { println("caught backtrack: defined(err) = ", defined(err)); }

try { throwString("hello"); }
catch err { println("caught throwString: ", err); }

try { throw; }
catch err { println("caught throw: defined(err) = ", defined(err)); }

try { throw "success"; }
catch err { println("caught throw \"success\": ", err); }

